### ISSUE TITLE
[NetherVinery] Crimson & Warped Grape Bushes not generating (possible mod incompatibility)

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#270]
### Minecraft Version

1.20.1

### Mod

NetherVinery

### Mod Version

1.2.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Neither the `nethervinery:crimson_grape_bush` nor `nethervinery:warped_grape_bush` features are generating in my modpack. I believe this is a compatibility issue with another mod after a few tests. See below.

I tested this on a minimal instance with just NetherVinery and its dependent mods, and the bushes spawned as intended. I tested this with all of the large world generation mods in my modpack (Continents, Tectonic, Regions Unexplored, Swampier Swamps, Incendium, Hearths, Cinderscapes, Nullscape, & TerraBlender), and the bushes still spawned as intended. While testing with all the mods in my modpack, however, the bushes did not spawn as intended.

Until there is more information on this, the issue should stay open in case any other players experience the same issue and happen to pinpoint the exact issue.

### Steps to Reproduce

1. Install NetherVinery, Scannable, and _[incompatible mod]_ (Scannable is only used to search for the grape bush blocks. Other methods can be used)
2. Increase the `"count"` parameter in both `data/nethervinery/worldgen/placed_feature/warped_grape_bush_chance.json` and `data/nethervinery/worldgen/placed_feature/crimson_grape_bush_chance.json` to around 150 or higher via datapack to make them more common so that it is easier to verify that they are generating
3. Enter The Nether in a creative world with the Default generation type
4. Use Scannable (or scanning method of choice) to attempt to search for grape bushes in compatible biomes (default are `minecraft:crimson_forest` for crimson bushes and `minecraft:warped_forest` for warped bushes)

Currently, the incompatible mod is unknown (assuming it is a mod compatibility issue).

### Logs

[latest.log](https://github.com/user-attachments/files/16903255/latest.log)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
As you have already noticed, the issue doesn't seem to be related to NetherVinery but rather to another mod that is affecting the world generation in some way.

For this reason, I am closing this issue. While I understand the intention behind "informing others," this issue is not connected to NetherVinery. I want to keep the issue section here as clean as possible, focusing only on current issues and those that I can actively resolve through my own code.

 It would be more productive to identify which mod is causing the spawns to be removed and report the issue there instead.

**Comment by bawat** [comment]
Unfortunately, I am having the same problem.
Fabric 1.20.1
Freshly generated world

Mod list:
architectury-9.2.14-fabric.jar
fabric-api-0.92.2+1.20.1.jar
fabric-carpet-1.20-1.4.112+v230608.jar
fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar
letsdo-API-fabric-1.2.15-fabric.jar
letsdo-herbalbrews-fabric-1.0.10.jar
letsdo-meadow-fabric-1.3.22.jar
letsdo-nethervinery-fabric-1.2.16.jar
letsdo-vinery-fabric-1.4.37.jar

**Comment by bawat** [comment]
`[15:57:35] [Render thread/ERROR]: Failed to register NetherVinery registries! Disabling mod.
java.lang.RuntimeException: Config 'class net.satisfy.vinery.fabric.config.VineryFabricConfig' has not been registered
	at me.shedaniel.autoconfig.AutoConfig.getConfigHolder(AutoConfig.java:77) ~[cloth-config-11.1.136-d18d228c921dbc21.jar:?]
	at net.satisfy.nethervinery.fabric.NetherVineryFabric.onInitialize(NetherVineryFabric.java:27) ~[letsdo-nethervinery-fabric-1.2.16.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.16.9.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.16.9-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]`
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=14,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=9,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=8,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=11,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=10,persistent=false,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=8,persistent=false,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=8,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=11,persistent=false,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=11,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=13,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=9,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=14,persistent=false,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=13,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=10,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=14,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=11,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=12,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=8,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=13,persistent=false,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=12,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=10,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=10,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=13,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=9,persistent=false,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=12,persistent=true,waterlogged=false'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=14,persistent=true,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=9,persistent=false,waterlogged=true'
[15:57:39] [Worker-Main-24/WARN]: Exception loading blockstate definition: 'vinery:blockstates/grapevine_leaves.json' missing model for variant: 'vinery:grapevine_leaves#distance=12,persistent=false,waterlogged=false'
