### ISSUE TITLE
Crash when effect gets saved

### ISSUE THREAD

**Issue by SiverDX** [satisfyu/Let-s-Do-Hub#282]
### Minecraft Version

1.21.1

### Mod

Farm and Charm

### Mod Version

1.2.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When you eat food which grants an effect from this mod and said effect gets saved (e.g. you hit ESC) the game will crash

(There are also a lot of recipe and tag (using `forge` namespace e.g.) errors

```
[16:15:53] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[16:15:53] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Saving entity NBT
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1744) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedPlayerList.save(IntegratedPlayerList.java:28) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:675) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:575) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.saveEverything(IntegratedServer.java:303) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}
Caused by: java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: minecraft:mob_effect@farm_and_charm:sustenance
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23122!/:?] {}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23122!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.effect.MobEffectInstance.save(MobEffectInstance.java:318) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.addAdditionalSaveData(LivingEntity.java:712) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.player.Player.addAdditionalSaveData(Player.java:841) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayer.addAdditionalSaveData(ServerPlayer.java:390) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1723) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	... 8 more
[16:15:53] [Server thread/FATAL] [ne.ne.ne.co.NeoForgeMod/]: Preparing crash report with UUID b27fbe81-7de2-4cc1-b80f-75f67ada9d95
[16:15:53] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\KaiZa\AppData\Roaming\PrismLauncher\instances\1.21.1 Test\.minecraft\crash-reports\crash-2024-09-17_16.15.53-server.txt
[16:15:53] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[16:15:53] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[16:15:53] [Render thread/FATAL] [ne.ne.ne.co.NeoForgeMod/]: Preparing crash report with UUID e2286faa-eb21-4c08-b42a-eddff1e13749
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-09-17 16:15:53
Description: Saving entity NBT

java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: minecraft:mob_effect@farm_and_charm:sustenance
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23122!/:?] {}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23122!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.effect.MobEffectInstance.save(MobEffectInstance.java:318) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.addAdditionalSaveData(LivingEntity.java:712) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.player.Player.addAdditionalSaveData(Player.java:841) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayer.addAdditionalSaveData(ServerPlayer.java:390) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1723) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedPlayerList.save(IntegratedPlayerList.java:28) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:675) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:575) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.saveEverything(IntegratedServer.java:303) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23122!/:?] {}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23122!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.effect.MobEffectInstance.save(MobEffectInstance.java:318) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.addAdditionalSaveData(LivingEntity.java:712) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.player.Player.addAdditionalSaveData(Player.java:841) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayer.addAdditionalSaveData(ServerPlayer.java:390) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
-- Entity being saved --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 5
	Entity Name: TheShadowX
	Entity's Exact location: -8.50, 122.00, -6.50
	Entity's Block location: World: (-9,122,-7), Section: (at 7,10,9 in -1,7,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1723) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedPlayerList.save(IntegratedPlayerList.java:28) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:675) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:575) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.saveEverything(IntegratedServer.java:303) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 1032632840 bytes (984 MiB) / 2222981120 bytes (2120 MiB) up to 10603200512 bytes (10112 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 12288.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5123
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 112066.63
	Virtual memory used (MiB): 39209.83
	Swap memory total (MiB): 79392.00
	Swap memory used (MiB): 1858.59
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 389438.88, total: 953056.00
	Space in storage for workdir (MiB): available: 389438.88, total: 953056.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10112m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['TheShadowX'/5, l='ServerLevel[New World]', x=-8.50, y=122.00, z=-6.50]]
	Active Data Packs: vanilla, mod_data, mod/doapi,terraform, mod/architectury (incompatible), mod/farm_and_charm (incompatible), mod/neoforge
	Available Data Packs: bundle, trade_rebalance, vanilla, mod/architectury (incompatible), mod/doapi,terraform, mod/farm_and_charm (incompatible), mod/neoforge, mod_data
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 3587236126892409231
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'neoforge'; Server brand changed to 'neoforge'
	Launched Version: 1.21.1
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.24.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.24.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.24.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		letsdo-API-forge-1.3.0-beta-release-forge.jar     |[Let's Do] API                |doapi                         |1.3.0-beta-release  |Manifest: NOSIGNATURE
		architectury-13.0.6-neoforge.jar                  |Architectury                  |architectury                  |13.0.6              |Manifest: NOSIGNATURE
		letsdo-farm_and_charm-neoforge-1.2.0-beta-release.|[Let's Do] Farm & Charm       |farm_and_charm                |1.2.0               |Manifest: NOSIGNATURE
		neoforge-21.1.54-universal.jar                    |NeoForge                      |neoforge                      |21.1.54             |Manifest: NOSIGNATURE
	Crash Report UUID: e2286faa-eb21-4c08-b42a-eddff1e13749
	FML: 4.0.24
	NeoForge: 21.1.54
```

### Steps to Reproduce

N/A

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
