### ISSUE TITLE
[F&C] Feeding Trough and Silo Issues

### ISSUE THREAD

**Issue by Acornrice** [satisfyu/Let-s-Do-Hub#286]
### Minecraft Version

Fabric 1.21.1

### Mod

Farm and Charm

### Mod Version

1.2.0 - beta - release [Modrinth]

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Can't add any kind of seeds, vanilla or modded, to the feeding trough.

Wooden Silos don't merge, duplicates and add ghost blocks. Ghost blocks appear after relog.

### Steps to Reproduce

https://github.com/user-attachments/assets/eb989cf8-bb16-4e20-b8be-8d1e01ea90c7

https://github.com/user-attachments/assets/402d5bb9-1e63-474d-9a3b-ef786eda9590

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by KalWantsPizza** [comment]
Adding to this - the Silos do not accept any ingredients to be dried at all. I've tested both Fabric and Neoforge 1.21.1

**Comment by FelixAgairu** [comment]
MC 1.21.1
Fabric Loader **0.16.9**
Farm and Charm **1.2.0**
Lets Do API **1.3.0**
Architectury **13.0.8**

Server got error while merge the Silos. 
Ghost blocks, can be seen after any block update incl. the relogin.
But all silos just not work.
```
[18:49:39] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@7311e647, suppressing error
java.lang.IllegalArgumentException: Cannot get property class_2746{name=open, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{farm_and_charm:silo_copper}
        at knot/net.minecraft.class_2688.method_11654(class_2688.java:97) ~[server-intermediary.jar:?]
        at knot/net.satisfy.farm_and_charm.block.entity.SiloBlockEntity.notifyMultiUpdated(SiloBlockEntity.java:172) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.satisfy.farm_and_charm.util.ConnectivityHandler.tryToFormNewMultiOfWidth(ConnectivityHandler.java:219) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.satisfy.farm_and_charm.util.ConnectivityHandler.tryToFormNewMulti(ConnectivityHandler.java:114) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.satisfy.farm_and_charm.util.ConnectivityHandler.formMulti(ConnectivityHandler.java:88) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.satisfy.farm_and_charm.util.ConnectivityHandler.formMulti(ConnectivityHandler.java:20) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.satisfy.farm_and_charm.block.entity.SiloBlockEntity.updateConnectivity(SiloBlockEntity.java:144) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.satisfy.farm_and_charm.block.SiloBlock.method_9615(SiloBlock.java:123) ~[letsdo-farm_and_charm-fabric-1.2.0-beta-release.jar:?]
        at knot/net.minecraft.class_4970$class_4971.method_26182(class_4970.java:1137) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2818.redirect$fhm000$worldedit$setBlockStateHook(class_2818.java:10303) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2818.method_12010(class_2818.java:273) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1937.method_30092(class_1937.java:232) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1937.method_8652(class_1937.java:217) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1747.method_7708(class_1747.java:153) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1747.method_7712(class_1747.java:76) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1747.mixinextras$bridge$method_7712$30(class_1747.java) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1747.wrapOperation$elb000$snowrealmagic$srm_useOn(class_1747.java:1544) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1747.method_7884(class_1747.java:46) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1799.method_7981(class_1799.java:373) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3225.method_14262(class_3225.java:372) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3244.method_12046(class_3244.java:1158) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2885.method_12547(class_2885.java:42) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2885.method_11054(class_2885.java:10) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
