### ISSUE TITLE
[Vinery] Conflict with mod Touhou little maid. Neoforge 1.21.1. WanderingWinemakerEntity.class

### ISSUE THREAD

**Issue by tipssssi** [satisfyu/Let-s-Do-Hub#314]
### Minecraft Version

1.21.1 

### Mod

Vinery

### Mod Version

1.5.0 neoforge

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

If u out lets do vinery and touhou little maids together = crash on world generation.
Problem in: WanderingWinemakerEntity.class
Mods can't work together because of this issue

### Steps to Reproduce

When starting world generation crash occurs (0% loading) Only in combination with mod touhou little maids

### Logs

Time: 2024-10-05 12:48:06
Description: Exception in server tick loop

java.lang.IllegalAccessError: failed to access class net.minecraft.world.entity.npc.VillagerTrades$ItemsForEmeralds from class net.satisfy.vinery.entity.WanderingWinemakerEntity (net.minecraft.world.entity.npc.VillagerTrades$ItemsForEmeralds is in module minecraft@1.21.1 of loader 'TRANSFORMER' @18f55704; net.satisfy.vinery.entity.WanderingWinemakerEntity is in module vinery@1.5.0-beta-release of loader 'TRANSFORMER' @18f55704)
	at TRANSFORMER/vinery@1.5.0-beta-release/net.satisfy.vinery.entity.WanderingWinemakerEntity.createTrades(WanderingWinemakerEntity.java:17) ~[letsdo-vinery-neoforge-1.5.0-beta-release.jar%23362!/:?] {re:classloading}
	at TRANSFORMER/vinery@1.5.0-beta-release/net.satisfy.vinery.entity.WanderingWinemakerEntity.<clinit>(WanderingWinemakerEntity.java:13) ~[letsdo-vinery-neoforge-1.5.0-beta-release.jar%23362!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.create(EntityType.java:1097) ~[client-1.21.1-20240808.144430-srg.jar%23292!/:?] {re:mixin,xf:fml:default,re:classloading,xf:fml:default,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType from mod architectury,pl:mixin:A}
	at TRANSFORMER/touhou_little_maid@1.1.12-hotfix2/com.github.tartaricacid.touhoulittlemaid.entity.misc.DefaultMonsterType.lambda$initDefault$0(DefaultMonsterType.java:38) ~[touhoulittlemaid-1.21-release-1.1.12-hotfix2.jar%23413!/:1.1.12-hotfix2] {re:classloading}
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
	at TRANSFORMER/touhou_little_maid@1.1.12-hotfix2/com.github.tartaricacid.touhoulittlemaid.entity.misc.DefaultMonsterType.initDefault(DefaultMonsterType.java:33) ~[touhoulittlemaid-1.21-release-1.1.12-hotfix2.jar%23413!/:1.1.12-hotfix2] {re:classloading}
	at TRANSFORMER/touhou_little_maid@1.1.12-hotfix2/com.github.tartaricacid.touhoulittlemaid.event.LevelLoadEvent.onLevelLoadEvent(LevelLoadEvent.java:17) ~[touhoulittlemaid-1.21-release-1.1.12-hotfix2.jar%23413!/:1.1.12-hotfix2] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23110!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23110!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.createLevels(MinecraftServer.java:375) ~[client-1.21.1-20240808.144430-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:337) ~[client-1.21.1-20240808.144430-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.initServer(IntegratedServer.java:77) ~[client-1.21.1-20240808.144430-srg.jar%23292!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670) ~[client-1.21.1-20240808.144430-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by sf178** [comment]
Not only this one, Minecolonies does it too

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
