### ISSUE TITLE
Vinery calls client code on 1.21.1

### ISSUE THREAD

**Issue by Leclowndu93150** [satisfyu/Let-s-Do-Hub#362]
### Minecraft Version

1.21.1 Fabric

### Mod

Vinery

### Mod Version

there is only ne

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

[17:17:55] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'doapi' at 'de.cristelknight.doapi.fabric.DoApiFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.satisfy.vinery.registry.ObjectRegistry
                at knot/net.satisfy.vinery.Vinery.init(Vinery.java:29) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at knot/net.satisfy.vinery.fabric.VineryFabric.onInitialize(VineryFabric.java:12) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
                at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/minecraft/class_638 [in thread "main"]
                at knot/net.satisfy.vinery.registry.ObjectRegistry.lambda$static$80(ObjectRegistry.java:145) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at knot/dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232) ~[architectury-13.0.8-fabric.jar:?]
                at knot/de.cristelknight.doapi.Util.registerItem(Util.java:50) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
                at knot/net.satisfy.vinery.registry.ObjectRegistry.registerItem(ObjectRegistry.java:345) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at knot/net.satisfy.vinery.registry.ObjectRegistry.<clinit>(ObjectRegistry.java:145) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at knot/net.satisfy.vinery.registry.StorageTypeRegistry.registerBlocks(StorageTypeRegistry.java:22) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at knot/net.satisfy.vinery.util.api.VineryDoApi.registerBlocks(VineryDoApi.java:22) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
                at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.getBlocksForEntity(DoApiBlockEntityTypes.java:45) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
                at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.lambda$static$0(DoApiBlockEntityTypes.java:24) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
                at knot/dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232) ~[architectury-13.0.8-fabric.jar:?]
                at knot/dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:78) ~[architectury-13.0.8-fabric.jar:?]
                at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.init(DoApiBlockEntityTypes.java:55) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
                at knot/de.cristelknight.doapi.DoApi.init(DoApi.java:15) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
                at knot/de.cristelknight.doapi.fabric.DoApiFabric.onInitialize(DoApiFabric.java:10) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
                ... 7 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
        at knot/net.satisfy.vinery.registry.ObjectRegistry.lambda$static$80(ObjectRegistry.java:145) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232) ~[architectury-13.0.8-fabric.jar:?]
        at knot/de.cristelknight.doapi.Util.registerItem(Util.java:50) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/net.satisfy.vinery.registry.ObjectRegistry.registerItem(ObjectRegistry.java:345) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/net.satisfy.vinery.registry.ObjectRegistry.<clinit>(ObjectRegistry.java:145) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/net.satisfy.vinery.registry.StorageTypeRegistry.registerBlocks(StorageTypeRegistry.java:22) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/net.satisfy.vinery.util.api.VineryDoApi.registerBlocks(VineryDoApi.java:22) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.getBlocksForEntity(DoApiBlockEntityTypes.java:45) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.lambda$static$0(DoApiBlockEntityTypes.java:24) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232) ~[architectury-13.0.8-fabric.jar:?]
        at knot/dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:78) ~[architectury-13.0.8-fabric.jar:?]
        at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.init(DoApiBlockEntityTypes.java:55) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/de.cristelknight.doapi.DoApi.init(DoApi.java:15) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/de.cristelknight.doapi.fabric.DoApiFabric.onInitialize(DoApiFabric.java:10) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.satisfy.vinery.registry.ObjectRegistry.lambda$static$80(ObjectRegistry.java:145) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232) ~[architectury-13.0.8-fabric.jar:?]
        at knot/de.cristelknight.doapi.Util.registerItem(Util.java:50) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/net.satisfy.vinery.registry.ObjectRegistry.registerItem(ObjectRegistry.java:345) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/net.satisfy.vinery.registry.ObjectRegistry.<clinit>(ObjectRegistry.java:145) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/net.satisfy.vinery.registry.StorageTypeRegistry.registerBlocks(StorageTypeRegistry.java:22) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/net.satisfy.vinery.util.api.VineryDoApi.registerBlocks(VineryDoApi.java:22) ~[letsdo-vinery-fabric-1.5.0-beta-release.jar:?]
        at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.getBlocksForEntity(DoApiBlockEntityTypes.java:45) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.lambda$static$0(DoApiBlockEntityTypes.java:24) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232) ~[architectury-13.0.8-fabric.jar:?]
        at knot/dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:78) ~[architectury-13.0.8-fabric.jar:?]
        at knot/de.cristelknight.doapi.common.registry.DoApiBlockEntityTypes.init(DoApiBlockEntityTypes.java:55) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/de.cristelknight.doapi.DoApi.init(DoApi.java:15) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at knot/de.cristelknight.doapi.fabric.DoApiFabric.onInitialize(DoApiFabric.java:10) ~[letsdo-API-fabric-1.3.0-beta-release-fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 6 more

### Steps to Reproduce

yk

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Duplicated Issue.
