### ISSUE TITLE
vinery .32 and .31 causes crash with nethervinery

### ISSUE THREAD

**Issue by uczpre** [satisfyu/Let-s-Do-Hub#386]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

doesnt happen with .30

### Steps to Reproduce

use .31 or .32  with newest ver of nether vinery

### Logs

[19:55:04] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'nethervinery' at 'net.satisfy.nethervinery.fabric.NetherVineryFabricPre'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'nethervinery' at 'net.satisfy.nethervinery.fabric.NetherVineryFabricPre'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: net/satisfy/vinery/registry/GrapeTypeRegistry
	at net.satisfy.nethervinery.registry.NetherGrapeTypes.<clinit>(NetherGrapeTypes.java:9) ~[letsdo-nethervinery-fabric-1.2.14.jar:?]
	at net.satisfy.nethervinery.util.NetherVineryPre.preInit(NetherVineryPre.java:7) ~[letsdo-nethervinery-fabric-1.2.14.jar:?]
	at net.satisfy.nethervinery.fabric.NetherVineryFabricPre.onPreLaunch(NetherVineryFabricPre.java:9) ~[letsdo-nethervinery-fabric-1.2.14.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.satisfy.vinery.registry.GrapeTypeRegistry
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.satisfy.nethervinery.registry.NetherGrapeTypes.<clinit>(NetherGrapeTypes.java:9) ~[letsdo-nethervinery-fabric-1.2.14.jar:?]
	at net.satisfy.nethervinery.util.NetherVineryPre.preInit(NetherVineryPre.java:7) ~[letsdo-nethervinery-fabric-1.2.14.jar:?]
	at net.satisfy.nethervinery.fabric.NetherVineryFabricPre.onPreLaunch(NetherVineryFabricPre.java:9) ~[letsdo-nethervinery-fabric-1.2.14.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by uczpre** [comment]
so .33 is fix attempt 3 or what ?

**Comment by satisfyu** [comment]
Chill out, man. I can understand that things like this can cause frustration, but you can still keep it together and refrain from making such comments.

It was clearly marked as incompatible and simply has to do with Vinery undergoing some refactors regarding class names and folder structure.

**Comment by satisfyu** [comment]
Just update NetherVinery to 1.2.15 and you will be fine.

**Comment by uczpre** [comment]
Oh shit, what did i say ? i think there's a cultural barrier between us, sorry. the attempt 3 comment is just a joke about a comment on the fixed issue section on the .32 changelog.

**Comment by uczpre** [comment]
so i assume all of your mods wont require letsdoapi on the next update ?

**Comment by uczpre** [comment]
Also, thanks a lot man ;D
