### ISSUE TITLE
Vinery/JEI crash

### ISSUE THREAD

**Issue by troglodyte06** [satisfyu/Let-s-Do-Hub#92]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.25

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When attempting to open the creative inventory whilst having JEI installed, the game crashes.
"java.lang.IllegalArgumentException: The stack count must be 1
	at net.minecraftforge.common.ForgeHooks.lambda$onCreativeModeTabBuildContents$17(ForgeHooks.java:1629) ~[forge-1.20.1-47.2.5-universal.jar%23451!/:?] {re:classloading}
	at net.minecraft.world.item.CreativeModeTab$Output.m_246326_(CreativeModeTab.java:414) ~[client-1.20.1-20230612.114412-srg.jar%23446!/:?] {re:classloading,pl:accesstransformer:B}
	at net.satisfy.vinery.registry.TabRegistry.lambda$static$1(TabRegistry.java:173) ~[letsdo-vinery-forge-1.4.25.jar%23398!/:?] {re:classloading}"

### Steps to Reproduce

Open the inventory with the latest version of the mod and JEI

### Logs

https://pastebin.com/VBV0EurF

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by troglodyte06** [comment]
Weird bug, idk where else to report

**Comment by satisfyu** [comment]
Fixed in 1.4.26
